Page({
  data: {
    iconSize: [20, 30, 40, 50, 60],
    iconColor: ["red", "yellow", "blue", "green"],
    iconType: [
      "home",
      "search",
      "calendar",
      "location",
      "setting",
      "contact",
      "chat",
      "info",
      "warning",
      "success",
      "plus",
      "minus",
      "geometry",
      "close",
      "close_circle",
      "more_horizontal",
      "arrow_right",
      "arrow_left",
      "arrow_down",
      "arrow_up",
      "bookmark",
      "app_home",
      "phone_home",
      "share",
      "warning_glyph",
      "success_glyph",
      "close_glyph",
      "question",
    ],
  },
});
